version: '2'
services:
  web:
    build:
      context: ./
      dockerfile: ./docker/web.docker
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"
    links:
      - app
  app:
    build:
      context: ./
      dockerfile: ./docker/app.docker
    volumes:
      - ./:/var/www
  database:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=homestead
    ports:
      - "3306:3306"